### ISSUE TITLE
No video seen during shrink mode/live preview while working with MS office

### ISSUE THREAD

**Issue by jakkaas** [gileli121/WindowTop#117]
I have seen this behavior while working with excel/word/edge.

Whenever I am watching a video full screen/not in full screen in shrink mode and I click on any document for editing, the video panel becomes blank while the audio is still coming.

Steps
1.Open excel
2.Open a youtube video and start it.
3.Shrink the window (the video is still seen)
4.Click on excel/word.
5.The audio is coming but the video is blank

(not sure issue with windowtop or something in my PC)

![image](https://user-images.githubusercontent.com/43289832/123888331-e49d2300-d970-11eb-8d81-0ee87cf66cfc.png)
![image](https://user-images.githubusercontent.com/43289832/123888332-e49d2300-d970-11eb-9ff8-3bffd74c3d95.png)
![image](https://user-images.githubusercontent.com/43289832/123888334-e5ce5000-d970-11eb-9414-2a845a6c57af.png)

**Comment by gileli121** [comment]
@jakkaas 
This is a known issue to me.

The issue is with chrome... 
Seems that chrome has some tricks to avoid using computer processing resources.
It tries to stop rendering in case it thinks that the window is invisible. 
This is in order to reduce hardware resources..

I tried to see how I can trick chrome and how to make it think that it's the window is visible to avoid the situation that chrome stops rendering. I did not found a perfect solution.

The only solution that I did will work only if your taskbar will not auto-hide itself.
In your case the solution is not working because from your screenshot, your taskbar does auto-hide...

To solve it you may need to disable the following option:
![image](https://user-images.githubusercontent.com/17680514/123896171-b6681500-d969-11eb-84de-69b76d5e8e5e.png)

But I think that you may not want to do it because you using the anchors.

Another workaround is something you can found here:
https://github.com/LorenzCK/OnTopReplica/issues/90#issuecomment-716216258

**Comment by jakkaas** [comment]
Thanks. Workaround works.

**Comment by gileli121** [comment]
@jakkaas 
I found how to trick google chrome in a way that it will keep playing the video in Shrink mode and without the need to do the workaround with #web-contents-occlusion flag 

Can you please restore this flag to the default value and test it again with the build that I posted here:
https://github.com/BiGilSoft/WindowTop/issues/146#issuecomment-924395154

Thanks

**Comment by jakkaas** [comment]
The test build is working correctly
 Thanks

**Comment by gileli121** [comment]
@jakkaas 
Thank you.
Did you revert the settings you did in google chrome before you tested it (I mean - did you disabled the workaround I told you to do)?
Did you test it on Windows 10 or on Windows 11?

**Comment by jakkaas** [comment]
Yes i reverted the settings on edge before testing. I tried with coursera videos. I am using windows 10

**Comment by gileli121** [comment]
@jakkaas 
Thanks, but according to my own tests that I did in VM, I found this issue:
https://github.com/BiGilSoft/WindowTop/issues/146#issuecomment-924723642

You did not get the issue also?
I changing now the hotfix implementation.

Please respond in https://github.com/BiGilSoft/WindowTop/issues/146 
instead of here..
I will ask you to test it again

Thank you

**Comment by gileli121** [comment]
@jakkaas 
Can you please test the new build in https://github.com/BiGilSoft/WindowTop/issues/146#issuecomment-924865004

?

Thanks!
