### ISSUE TITLE
Having trouble witht start up by admin privileges

### ISSUE THREAD

**Issue by AiraPaul** [gileli121/WindowTop#351]
![IssureOFWindowtop](https://github.com/WindowTop/WindowTop-App/assets/84266985/d59666dc-f80a-4b61-85c8-71195bc3b086)
When I enable Start with Windows and Start with admin privilege，the windowtop.exe in Startup of task manager disappear,and windowtop do not start up when I restart my computer,if I disable the Start with admin privilege,and enable Start with Windows,I can see windowtop.exe in Startup of task manager,I tried on all my device even the VMware System,also the same problem,ps:I see the task schedual the windowtop made is invalid ,the problem also happen in before version .

**Comment by gileli121** [comment]
@AiraPaul 
Thanks for the report.
Something is not working right on my side, as well.
When the second checkbox is also enabled, it will create the task in the task scheduler because the task scheduler runs programs as an admin. The task is configured to start when the user is logged into Windows.

But when I run it from the task scheduler, I don't see the windowtop started.
It seems like a bug.

I am investigating it.

Thanks for the report.

**Comment by gileli121** [comment]
@AiraPaul 
I have no idea when it broke, but it seems that the issue is that the task created in the task scheduler is invalid.

I will work now on a fix.

For now, you can manually fix it by editing this task
You will need to modify the settings here so it will look like this (when I marked it in red)
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/d55c105d-a15d-4276-b27b-4cb99adc82e8)
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/132624e3-e6ce-4a51-a974-e32997f2fcae)

In the path, browse again to WindowTop, and in "Add arguments," write only `runby_schtasks` as in the screenshot.


After doing it, WindowTop should start as admin when Windows starts.
I checked it.


I will fix this bug that causes the app to create invalid tasks.
Thanks for the report.

**Comment by gileli121** [comment]
@AiraPaul 
Fixed.
Please try this version with the hotfix included:

https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.8

Try to disable and re-enable the option again, and let me know if it works well for you.
Enjoy

**Comment by AiraPaul** [comment]
It work,thanks

**Comment by gileli121** [comment]
Great!
Closed
