### ISSUE TITLE
The dark mode performs poorly in Wechat.

### ISSUE THREAD

**Issue by HoeYeungHo** [gileli121/WindowTop#363]
The Windows version of Wechat does not support dark mode. I plan to use Windows Top as an alternative solution, but it cannot accurately recognize the images in the avatar, resulting in poor performance. I hope for improvement!

![image](https://github.com/WindowTop/WindowTop-App/assets/60749707/43ba2aef-21cd-40ef-9263-4b7bc75992ba)

**Comment by gileli121** [comment]
Sorry for the late reply.
Anything about the image detection algorithm is a huge effort.
I hope to figure out how to improve it more, but I can't guarantee that I will be able to.
This is not an easy problem

**Comment by wwxiaoqi** [comment]
Because WeChat consists of two different windows. If you use a related window capture tool, you will notice that it is composed of two interfaces combined together.

1. Wechat ontology UI interface
2. WeChatAppEx  A web page window

It's put together like this:
![image](https://github.com/user-attachments/assets/ee1e4f18-ec8a-4706-89db-a15916a48ac0)

![image](https://github.com/user-attachments/assets/8302c260-99b3-4361-abf5-cc0bcddbcdf3)

WeChatAppEx is actually a webview browser. For this type, there might not be a good solution unless it can be tricked into thinking it’s in dark mode.

**Comment by HoeYeungHo** [comment]
I am very excited that WeChat finally supports dark mode! WindowTop will continue to enable other software that cannot adapt well to dark mode to work better at night!

**Comment by Luminphantom** [comment]
目前windows端的微信已经可以在官网下载测试版，测试版的微信支持了深色模式，可以不需要使用windowtop的深色模式替代了
