### ISSUE TITLE
Anchor mode with Win+D

### ISSUE THREAD

**Issue by julystone** [gileli121/WindowTop#381]
After switching back to the desktop using the Windows shortcut "win+D", the anchors on the right side unexpectedly vanished.

I'm not certain if my comprehension of anchors is accurate; I had assumed that all apps would generate anchors on the right.
However, now the anchors have completely disappeared.

**Comment by gileli121** [comment]
Hello, when you press Win+D, all windows are minimized.
When a window is minimized, its anchor also disappears, and this is the expected behavior.
Anchors are designed to show only if their window is not minimized and fully behind another window.


Why do you want the anchor to still appear when the window is minimized?

**Comment by gileli121** [comment]
Closed due to inactivity
