### ISSUE TITLE
feature request: dark mode keeps color after program restart

### ISSUE THREAD

**Issue by DavidHJong** [gileli121/WindowTop#385]
Dark mode has an option to keep color. but it can only keeps color while the program is running and cease to work after program restarts. It would be better to keep color for specific program consistently.

**Comment by gileli121** [comment]
@DavidHJong

You can enable the "Keep colors" filter by default for any app when you activate dark mode. To do this, follow these screenshots:

![image](https://github.com/user-attachments/assets/48aafce8-bf2d-4379-b4b6-4b014ab87238)  
![image](https://github.com/user-attachments/assets/dec36ab8-f5b9-4467-b652-f916202d913e)

Please note that this change will only affect new windows (those opened after you modify these settings). Alternatively, you can restart WindowTop.

If the filter does not work, it may be due to a saved configuration for that window. To ensure there’s no saved configuration, open the toolbar menu for that window. If you see an option to delete the configuration under the arrow as shown below:
![image](https://github.com/user-attachments/assets/3ea13687-93bf-4db5-8995-567a9728437c)

Then click it to remove it. Another option is to enable the "Keep colors" setting and then click save again; this will update the configuration with the filter enabled.

**Comment by DavidHJong** [comment]
Thank you, it works.

**Comment by gileli121** [comment]
Great
Enjoy!
