### ISSUE TITLE
Suggestions: sliding Slider to control blur in smart transparency

### ISSUE THREAD

**Issue by jakkaas** [gileli121/WindowTop#58]
Please provide smooth sliding slider to control blur in smart transparency instead of just 0, medium and 100 % just like in previous version.

Thanks

**Comment by gileli121** [comment]
This is too hard to implement in a way that it will work fine.
The reason it was done in the old version was that it was done badly and did not work well.
I switched to use Windows API for the blur effect instead of using my own that is not native and as a result, takes much more CPU usage and worked slow
