### ISSUE TITLE
5.0.0.1 won't start at all

### ISSUE THREAD

**Issue by avansteenbruggen** [gileli121/WindowTop#60]
Hello,

Want to try this app, looks amazing, but it wil not start.
I'm using Malewarebytes in wich already exculded the wintop folder.
tryed Start as admin, but the exe starts and then closes again.

any ideas?

**Comment by gileli121** [comment]
Thanks for the report!
Note that it is very first beta version so we may expect some big issues :) 

If you want to use this app now, you can download https://github.com/gileli121/WindowTop/releases/tag/v4.1.x 
That is not beta

About your issue, let me see how we can troubleshoot it.
I will create another build that save to log file so we should see errros in the log and I hope that it will help

**Comment by gileli121** [comment]
@avansteenbruggen 
Luckily for us, I was able to reproduce your issue :)

If you don't have the folder "WindowTop" under %AppData% you will get this issue.
For now, the workaround for your issue is to do these steps:

1. Go to %AppData% folder:
![image](https://user-images.githubusercontent.com/17680514/111487517-1a5f2880-8741-11eb-9c1f-c927149dae4f.png)
2. Under %AppData% folder, create new folder called "WindowTop"
![image](https://user-images.githubusercontent.com/17680514/111487660-39f65100-8741-11eb-9ece-c88267d1bd0c.png)
3. Start WindowTop again

Let me know if it fixed.

**Comment by avansteenbruggen** [comment]
That was the problem :) thnx for the quick reponse, working now :)
