### ISSUE TITLE
Question / Feature request: Check key state

### ISSUE THREAD

**Issue by WZ-Tong** [gileli121/WindowTop#78]
After upgrading from v4 to v5 early this year (at that time the v5 is still in beta channel), the software noticed me that I don't have a key. So I activated it again.

This time when I upgrade to v5 stable, the software gives me an alert saying there is a problem to the key and if I want to continue, maybe an activate count will lose.

So I wander how many **other** computers I can activate. Maybe the count can be displayed in the activate page?

**Comment by gileli121** [comment]
Hello, 
In old versions before v5, there was a bug that multiple computers detected as one computer and as a result, you could register the key with more than the maximum allowed usage amount.

This bug was fixed in v5.
But it caused another issue:
The new version generates another ID for the computer and it is in addition to the buggy ID that was generated for multiple different computers.

This caused an issue that the usage count was increased.

To solve this problem I restarted the database in the license server.
Now the usage count of all license keys restarted.

You should not have problem anymore now

**Comment by WZ-Tong** [comment]
Thanks
